export default [
  { "name": "sandwiches", 
  "url": "/menu/lunch",
  "newUrl": "/menu/lunch/sandwiches",
  "id": "1" },
  { "name": "breakfasts", 
  "url": "/menu/lunch",
  "newUrl": "/menu/lunch/breakfasts",
  "id": "2" },
  { "name": "main courses", 
  "url": "/menu/lunch",
  "newUrl": "/menu/lunch/courses",
  "id": "3" },
  { "name": "appetizers", 
  "url": "/menu/lunch",
  "newUrl": "/menu/lunch/appetizers",
  "id": "4" },
  { "name": "desserts&drinks", 
  "url": "/menu/lunch",
  "newUrl": "/menu/lunch/desserts",
  "id": "5" },
  { "name": "grill", 
  "url": "/menu/lunch",
  "newUrl": "/menu/lunch/grill",
  "id": "6" },
  { "name": "sopa", 
  "url": "/menu/dinner",
  "newUrl": "/menu/dinner/sopa",
  "id": "7" },
  { "name": "ensaladas", 
  "url": "/menu/dinner",
  "newUrl": "/menu/dinner/ensaladas",
  "id": "8" },
  { "name": "carne", 
  "url": "/menu/dinner",
  "newUrl": "/menu/dinner/carne",
  "id": "9" },
  { "name": "pescado", 
  "url": "/menu/dinner",
  "newUrl": "/menu/dinner/pescado",
  "id": "10" },
  { "name": "vino blanco", 
  "url": "/menu/wine",
  "newUrl": "/menu/wine/blanco",
  "id": "11" },
  { "name": "vino tinto", 
  "url": "/menu/wine",
  "newUrl": "/menu/wine/tinto",
  "id": "12" },
  { "name": "vino rosado", 
  "url": "/menu/wine",
  "newUrl": "/menu/wine/rosado",
  "id": "13" },
  { "name": "un vino espumoso", 
  "url": "/menu/wine",
  "newUrl": "/menu/wine/espumoso",
  "id": "14" }
]

